version: '3.8'

services:
  ecotracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=sqlite:///app/data/database.sqlite
      - JWT_SECRET=dev-secret-key-change-this
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./server:/app/server
      - ./frontend:/app/frontend
      - ecotracker_dev_data:/app/data
      - /app/server/node_modules
      - /app/frontend/node_modules
    command: npm run dev
    restart: unless-stopped
    networks:
      - ecotracker-dev-network

  nginx-dev:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - ecotracker
    restart: unless-stopped
    networks:
      - ecotracker-dev-network

volumes:
  ecotracker_dev_data:
    driver: local

networks:
  ecotracker-dev-network:
    driver: bridge
